apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: openshift-gitops
spec:
  destination:
    namespace: "{{ $.Values.development.kafka.namespace }}"
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: "{{ $.Values.development.kafka.contextDir }}"
    repoURL: "{{ $.Values.development.repoUrl }}"
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true