apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globex
  namespace: openshift-gitops
spec:
  destination:
    namespace: "{{ $.Values.production.globex.namespace }}"
    server: 'https://kubernetes.default.svc'
  project: default
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
      kind: ServiceAccount
  source:
    path: "{{ $.Values.production.globex.contextDir }}"
    repoURL: "{{ $.Values.production.repoUrl }}"
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
